import { VariantMap } from '../types/variantType';

const VALUES = [
  'min',
  'max',
  'fit',
  'auto',
  'full',
  '1/12',
  '2/12',
  '3/12',
  '4/12',
  '5/12',
  '6/12',
  '7/12',
  '8/12',
  '9/12',
  '10/12',
  '11/12',
  1,
  2,
  3,
  4,
  10,
  12,
  16,
  20,
  24,
  32,
  40,
  48,
  56,
  64,
  80,
  96,
  140,
  192,
  256,
  320,
  392,
  440,
  520,
  640,
] as const;

const sizing = {
  width: { prefix: 'w', values: VALUES, responsive: true },
  minWidth: { prefix: 'min-w', values: VALUES, responsive: true },
  maxWidth: { prefix: 'max-w', values: VALUES, responsive: true },
  height: { prefix: 'h', values: VALUES, responsive: true },
  minHeight: { prefix: 'min-h', values: VALUES, responsive: true },
  maxHeight: { prefix: 'max-h', values: VALUES, responsive: true },
  size: { prefix: 'size', values: VALUES, responsive: true },
} satisfies VariantMap;

export default sizing;
