import React from 'react';
import {
  PolymorphicComponentPropWithRef,
  PolymorphicRef,
} from '../../types/polymorphicTypes';
import { VariantProps } from '../../types/variantType';
import flexVariants from './variants';

type FlexElements = 'div' | 'span' | 'nav' | 'ul' | 'li';
export type FlexProps = PolymorphicComponentPropWithRef<
  FlexElements,
  VariantProps<typeof flexVariants>
>;

const Flex = React.forwardRef(
  (props: FlexProps, ref: PolymorphicRef<FlexElements>) => {
    const {
      as,
      className,
      m,
      mb,
      mt,
      ms,
      me,
      mx,
      my,
      p,
      pt,
      pb,
      ps,
      pe,
      px,
      py,
      gap,
      gapX,
      gapY,
      spaceX,
      spaceY,
      top,
      left,
      bottom,
      right,
      display = 'flex',
      position,
      opacity,
      aspectRatio,
      border,
      radius,
      borderStyle,
      borderBottom,
      borderTop,
      borderLeft,
      borderRight,
      width,
      height,
      size,
      scale,
      scaleX,
      scaleY,
      origin,
      rotate,
      translateX,
      translateY,
      transition,
      transitionDuration,
      transitionDelay,
      transitionTimingFunction,
      cursor,
      pointer,
      resize,
      borderColor,
      backgroundColor,
      alignContent,
      alignItems,
      alignSelf,
      justifyContent,
      justifySelf,
      justifyItems,
      placeSelf,
      flex,
      flexBasis,
      flexDirection,
      flexWrap,
      gridRowSpan,
      gridColumnSpan,
      gridRowStart,
      gridRowEnd,
      gridColumnStart,
      gridColumnEnd,
      pseudos,
      ...rest
    } = props;
    const Component = (as || 'div') as React.ElementType;

    return (
      <Component
        ref={ref}
        className={flexVariants({
          m,
          mb,
          mt,
          ms,
          me,
          mx,
          my,
          p,
          pt,
          pb,
          ps,
          pe,
          px,
          py,
          gap,
          gapX,
          gapY,
          spaceX,
          spaceY,
          top,
          left,
          bottom,
          right,
          display,
          position,
          opacity,
          aspectRatio,
          border,
          radius,
          borderStyle,
          borderBottom,
          borderTop,
          borderLeft,
          borderRight,
          width,
          height,
          size,
          scale,
          scaleX,
          scaleY,
          origin,
          rotate,
          translateX,
          translateY,
          transition,
          transitionDuration,
          transitionDelay,
          transitionTimingFunction,
          cursor,
          pointer,
          resize,
          alignContent,
          alignItems,
          alignSelf,
          justifyContent,
          justifySelf,
          justifyItems,
          placeSelf,
          flex,
          flexBasis,
          flexDirection,
          flexWrap,
          pseudos,
          borderColor,
          backgroundColor,
          gridRowSpan,
          gridColumnSpan,
          gridRowStart,
          gridRowEnd,
          gridColumnStart,
          gridColumnEnd,

          className,
        })}
        {...rest}
      />
    );
  }
);

export default Flex;
